services:
  dev-database:
    image: postgres:15.2
    container_name: dev-database
    ports:
      - 5434:5432 #{port in my pc}:{port in container}
    environment:
      POSTGRES_DB: socialdb
      POSTGRES_USER: danlaanh202
      POSTGRES_PASSWORD: danlaanh202
    networks:
      - nestjs-network
networks:
  nestjs-network:
